name: Python package

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.6.14"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Format check with ruff
        run: |
          uv run ruff format . --diff

      - name: Lint check with ruff
        run: |
          uv run ruff check . --output-format=github

      - name: Test with pytest
        run: |
          uv run pytest -vv --cov-report term-missing --cov-report xml --cov utah-districts

      #- name: Upload coverage to Codecov
      #  uses: codecov/codecov-action@v5
      #  env:
      #    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}